version: '3.8'

services:
  openhands:
    build:
      context: .
      dockerfile: Dockerfile
    image: openhands:latest
    container_name: openhands-app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RUNTIME=local
      - DEBUG=1
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=12000
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=12001
      - DISABLE_AUTH=true
      - ENABLE_SECURITY=false
      - OPENHANDS_WORKSPACE_BASE=/app/workspace
      - OPENHANDS_CONFIG_DIR=/app/.openhands
    ports:
      - "12000:12000"
    volumes:
      - ./workspace:/app/workspace
      - ./.openhands:/app/.openhands
    restart: unless-stopped
    command: >
      bash -c "unset SESSION_API_KEY && 
      cd /app && 
      poetry run uvicorn openhands.server.listen:app --host 0.0.0.0 --port 12000"