version: '3'

services:
  openhands:
    build:
      context: .
      dockerfile: Dockerfile
    image: openhands:latest
    container_name: openhands-app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RUNTIME=local
      - DEBUG=1
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=3000
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=3001
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./workspace:/app/workspace
      - ./.openhands:/.openhands
    command: >
      bash -c "cd /app && 
      poetry run uvicorn openhands.server.listen:app --host 0.0.0.0 --port 3000"